/* Number of total semesters: */
window.semesters = 8;

/* List of available colors to toggle a course as completed */
/* The first color is default for selecting options as well, so make sure to choose that one wisely */
window.colors = ["#b1fca4", "#fac6ff", "#a8c9ff", "#ff6347", "#9400d3", "#19dfda", "#ff7373", "#223bf6"];


window.courses = [
    [
    { name: "Biologia Molecular", credits: 1, code: "BMH126", semester: 1},
    { name: "Embriologia", credits: 1, code: "BMH127", semester: 1},
    { name: "Bioquímica I", credits: 3, code: "BQM101", semester: 1},
    { name: "ICF", credits: 2, code: "FFC111", semester: 1},
    { name: "Metodologia Científica", credits: 2, code: "FFP111", semester: 1},
    { name: "Biofísica", credits: 3, code: "FFW112", semester: 1, corequirements: [1]},
    { name: "Química Geral I", credits: 4, code: "IQG114", semester: 1},
    { name: "Cálculo p/ Farmácia", credits: 3, code: "MAC108", semester: 1},
    { name: "PCI I ", credits: 8, code: "BMW203", semester: 2, requirements: [0, 2]},
    { name: "Bioquímica II", credits: 4, code: "BQM103", semester: 2, requirements: [2]},
    { name: "Química Geral II", credits: 3, code: "IQG127", semester: 2, requirements: [6]},
    { name: "Química Orgânica I", credits: 4, code: "IQO120", semester: 2, requirements: [6]},
    { name: "Bioestatística", credits: 3, code: "MAD237", semester: 2},
    { name: "Atividades Acad. Optativas", credits: 2, semester: 2},
    { name: "PCI II", credits: 11, code: "BMW204", semester: 3, requirements: [8]},
    { name: "Química Analítica I", credits: 2, code: "IQA123", semester: 3, requirements: [6], corequirements: [16]},
    { name: "Química Analítica Exp. I", credits: 2, code: "IQA124", semester: 3, requirements: [6], corequirements: [15]},
    { name: "Físico-Química ", credits: 4, code: "IQF235", semester: 3, requirements:[7]},
    { name: "Química Orgânica II", credits: 3, code: "IQO230", semester: 3, requirements:[11]},
    { name: "Química Orgânica Exp. I", credits: 2, code: "IQO242", semester: 3, requirements: [10, 11]},
    { name: "Farmacobotânica", credits: 3, code: "FFP600", semester: 4},
    { name: "Iniciacao Científica", credits: 2, code: "FFP111", semester: 4, requirements: [4]},
    { name: "Química Analítica II", credits: 2,code: "IQA233", semester: 4, requirements: [15, 16], corequirements: [23]},
    { name: "Química Analítica Exp. II", credits: 2, code: "IQA234", semester: 4, requirements: [15, 16], corequirements: [22]},
    { name: "Bioinorgânica", credits: 4, code: "IQG234", semester: 4, requirements: [10]},
    { name: "Métodos Espectrométricos", credits: 3, code: "IQO220", semester: 4, requirements: [18, 19]},
    { name: "Química Orgânica III", credits: 3, code: "IQO240", semester: 4, requirements: [18]},
    { name: "Atividades Acad. Optativas", credits: 3, semester: 4},
    { name: "Farmacocinética e Farmacodinâmica", credits: 2, code: "BMF310", semester: 5, requirements: [9, 14]},
    { name: "Saúde Coletiva", credits: 2, code: "FFC303", semester: 5},
    { name: "Análises Farmacêuticas", credits: 5, code: "FFM302", semester: 5, requirements: [17, 22, 23]},
    { name: "Política de Saúde", credits: 2, code: "FFM311", semester: 5},
    { name: "Microbiologia e Imunologia", credits: 8, code: "IMW360", semester: 5, requirements: [2]},
    { name: "Química Orgânica Exp. II", credits: 2, code: "IQO251", semester: 5, requirements: [19, 25, 26]},
    { name: "Atividades Acad. Optativas", credits: 2, semester: 5},
    { name: "Farmacologia Neuroendócrina", credits: 4, code: "BFM320", semester:6, requirements: [14, 28]},
    { name: "Parasitologia", credits: 3, code: "CFP215", semester: 6, requirements: [14, 32]},
    { name: "Micro Imuno Clínica", credits: 3, code: "FFC480", semester: 6, requirements: [32]},
    { name: "Metabolismo Integrado", credits: 4, code: "FFI311", semester: 6, requirements: [9]},
    { name: "Farmacotécnica I", credits: 4, code: "FFM313", semester: 6, requirements: [28]},
    { name: "Farmacognosia I", credits: 3, code: "FFP313", semester: 6, requirements: [20, 26]},
    { name: "Química de Alimentos", credits: 3, code: "FFP324", semester: 6, requirements: [9, 22]},
    { name: "Farmacologia Cardio/Quimio", credits: 4, code: "BMF410", semester: 7, requirements: [14, 35]},
    { name: "Bioquímica Clínica", credits: 3, code: "FFC304", semester: 7, requirements: [9, 14]},
    { name: "Diagnóstico Clínico Laboratorial", credits: 2, code: "FFC321", semester: 7, requirements: [32, 36]},
    { name: "Hematologia", credits: 2, code: "FFC322", semester:7, requirements: [14]},
    { name: "Farmacotécnica II", credits: 4, code: "FFM323", semester: 7, requirements: [39]},
    { name: "Assist. e Atenção Farm.", credits: 2, code: "FFM481", semester: 7, requirements: [35, 39]},
    { name: "Estágio Sup. Farm. Comun.", credits: 2, code: "FFM481", semester: 7, requirements: [28, 39]},
    { name: "Farmacognosia II", credits: 3, code: "FFP323", semester: 7, requirements: [40]},
    { name: "Análises de Alimentos", credits: 3, code: "FFP403", semester: 7, requirements: [41]},
    { name: "Parasitologia e Micologia Clínica", credits: 3, code: "FFC406", semester: 8, requirements: [36]},
    { name: "Química Farm. Med.", credits: 5, code: "FFI401", semester: 8, requirements: [26, 42]},
    { name: "Farmácia Hospitalar", credits: 2, code: "FFM300", semester: 8, corequirements: [42, 46]},
    { name: "Deonto. e Legisl. Farmacêutica", credits: 2, code: "FFM301", semester: 8},
    { name: "Farmaco-epidemiologia", credits: 2, code: "FFM402", semester: 8, requirements: [12, 29]},
    { name: "Farmacotécnica Hospitalar", credits: 2, code: "FFM403", semester: 8, requirements: [46], corequirements: [53]},
    { name: "Tecnologia Ind. Farm.", credits: 4, code: "FFM408", semester: 8, requirements: [10, 39]},
    { name: "Estág. Sup. Farm. Manip. Alopática", credits: 2, code: "FFMU07", semester: 8, corequirements: [42, 46]},
    { name: "Bromatologia em Saúde", credits: 3, code: "FFP402", semester: 8, requirements: [41]},
    { name: "Atividades Acad. Livre. Esc.", credits: 2, semester: 8},
    { name: "Atividades Acad. Optativas", credits: 2, semester: 8},
    { name: "Toxicologia Geral", credits: 3, code: "FFC314", semester: 9, requirements:[26, 28]},
    { name: "Con. Bio. Micro. Quali. Pro. Farma.", credits: 4, code: "FFI402", semester: 9, requirements:[28, 32]},
    { name: "Biofarmácia", credits: 2, code: "FFM405", semester: 9, requirements: [46]},
    { name: "Dermocosméticos", credits: 2, code: "FFM406", semester: 9, requirements: [39]},
    { name: "Biotecnologia Farmacêutica", credits: 3, code: "FFM426", semester: 9, requirements: [32, 38]},
    { name: "Estágio Sup. Farmácia Hosp.", credits: 2, code: "FFMU08", semester: 9, requirements: [42, 46, 53]},
    { name: "TCC", credits: 0, code: "FFWK02", semester: 9, requirements: [21]},
    { name: "Economia e Adm, Empr. Farm.", credits: 3, code: "IEEE326", semester: 9},
    { name: "Atividades Acad. Livre. Esc.", credits: 3, semester: 9},
    { name: "Atividades Acad. Optativas", credits: 6, semester: 9, step: 1},
    { name: "Estágio Sup Especialidades", credits:8, code: "FFWU06", semester: 10},
    ],
    [
    /*0*/ { name: "Gramática Txt L. Inglesa", credits: 5, code: "LEG113", semester: 1, category: 1, workload: 90},  
    /*1*/ { name: "Intro. L. Grega", credits: 4, code: "LEC111", semester: 1, category: 1, workload: 60},
    /*2*/ { name: "Prod. Leitura Txt. em LP", credits: 2, code: "LEV113", semester: 1, category: 1, workload: 60}, 
    /*3*/ { name: "Intro. L. Latina", credits: 4, code: "LEC160", semester: 1, category: 1, workload: 60},
    /*4*/ { name: "Fund. Linguística", credits: 4, code: "LEF140", semester: 1, category: 1, workload: 60},
    /*5*/ { name: "Teoria Literária I", credits: 4, code: "LEL100", semester: 1, category: 1, workload: 60},
    /*6*/ { name: "Prod. Escrita L. Inglesa", credits: 3, code: "LEG122", semester: 2, requirements: [0], category: 1, workload: 60},
    /*7*/ { name: "Intro. Lit. Grega", credits: 4, code: "LEC115", semester: 2, requirements: [1], workload: 60},
    /*8*/ { name: "Variação da LP", credits: 4, code: "LEV100", semester: 2, category: 1, workload: 60},
    /*9*/ { name: "Oratória Latim", credits: 4, code: "LEC166", semester: 2, requirements: [3], category: 1, workload: 60},
    /*10*/ { name: "Fund. Análise Fonológica", credits: 4, code: "LEF150", semester: 2, requirements: [4], workload: 60},
    /*11*/ { name: "Teoria Literária II", credits: 4, code: "LEL110", semester: 2, workload: 60},
    /*12*/ { name: "Filosofia Educ. Mundo Ocid.", credits: 4, code: "EDF120", semester: 2, workload: 60},    
    /*13*/ { name: "Aq. Inglês Segunda L.", credits: 4, code: "LEG112", semester: 3, requirements: [0,6], category: 1, workload: 60},
    /*14*/ { name: "Intro. Lit. L. Inglesa", credits: 4, code: "LEG231", semester: 3, requirements: [0,6], category: 1, workload: 60},
    /*15*/ { name: "Fonologia da LP", credits: 4, code: "LEV112", semester: 3, requirements: [2,8], category: 1, workload: 60},
    /*16*/ { name: "Lírica Latim", credits: 4, code: "LEC262", semester: 3, requirements: [9], category: 1, workload: 60},
    /*17*/ { name: "Fund. Análise Sintática", credits: 4, code: "LEF240", semester: 3, requirements: [4], workload: 60},
    /*18*/ { name: "Fund. Cult. Lit. Brasileira", credits: 2, code: "LEL287", semester: 3, requirements: [5], workload: 60},
    /*19*/ { name: "Educ. Linguística L. Inglesa", credits: 3, code: "LEG241", semester: 4, requirements: [13,14], category: 1, workload: 60},
    /*20*/ { name: "Narrativa L. Inglesa I", credits: 4, code: "LEG222", semester: 4, category: 1, requirements: [13,14], workload: 60},
    /*21*/ { name: "Morfologia da LP", credits: 4, code: "LEV200", semester: 4, requirements: [2,8,15], category: 1, workload: 60},
    /*22*/ { name: "Ling. Lit. Latim: Narrativa", credits: 4, code: "LEC266", semester: 4, requirements: [16], workload: 60},
    /*23*/ { name: "Linguística e suas Aplicações", credits: 2, code: "LEF244", semester: 4, requirements: [4], workload: 30},
    /*24*/ { name: "Teoria Literária III", credits: 4, code: "LEL230", semester: 4, workload: 60},
    /*25*/ { name: "Fonologia da L. Inglesa", credits: 4, code: "LEG301", semester: 5, requirements: [13,14], category: 1, workload: 60},
    /*26*/ { name: "Narrativa em Língua Inglesa II", credits: 4, code: "LEG322", semester: 5, category: 1, workload: 60},
    /*27*/ { name: "Morfossintaxe da LP", credits: 4, code: "LEV210", semester: 5, requirements: [2,8,15,21], category: 1, workload: 60},
    /*28*/ { name: "Lit. Brasileira I: Poesia", credits: 4, code: "LEV266", semester: 5, category: 1, workload: 60},
    /*29*/ { name: "Poesia Portuguesa", credits: 4, code: "LEV343", semester: 5, workload: 60},
    /*30*/ { name: "Lit. Comparada", credits: 4, code: "LEL236", semester: 5, category: 1, workload: 60},
    /*31*/ { name: "Gramática da L. Inglesa", credits: 4, semester: 6, code: "LEG311", requirements: [25], category: 1, workload: 60},
    /*32*/ { name: "Poesia em Língua Inglesa", credits: 4, code: "LEG330", requirements: [13,14], semester: 6, category: 1, workload: 60},
    /*33*/ { name: "Sintaxe da LP", credits: 4, code: "LEV300", semester: 6, requirements: [2,8,15,21,27], category: 1, workload: 60},
    /*34*/ { name: "Lit. Brasileira II: Ficção", credits: 4, code: "LEV309", semester: 6, category: 1, workload: 60},
    /*35*/ { name: "Narrativa Portuguesa", credits: 4, code: "LEV450", semester: 6, category: 1, workload: 60},
    /*36*/ { name: "Tradução em L. Inglesa", credits: 4, code: "LEG472", requirements: [2,8,15,21,27], semester: 7, category: 1, workload: 60},
    /*37*/ { name: "Drama em Língua Inglesa", credits: 4, code: "LEG422", requirements: [2,8,15,21,27], semester: 7, category: 1, workload: 60},
    /*38*/ { name: "Semântica da LP", credits: 4, code: "LEV400", requirements: [2,8,15,21,27,33], semester: 7, category: 1, workload: 60},
    /*39*/ { name: "Temas e Prob. Lit. Brasileira", credits: 2, semester: 7, requirements: [34], category: 1, workload: 60},
    /*40*/ { name: "Atividades Acad. Optativas", credits: 5, semester: 7, step: 1, category: 2, workload: 120},
    /*41*/ { name: "PROJETO DE EXTENSÃO", credits: 160, code: "LEWX01", semester: 7, category: 1, workload: 160},
    /*42*/ { name: "L. Inglesa e Proc. de Global", credits: 4, code: "LEG401", semester: 8, requirements: [35], category: 1, workload: 60},
    /*43*/ { name: "A Literatura do Renascimento", credits: 4, code: "LEG430", semester: 8, requirements: [36], category: 1, workload: 60},
    /*44*/ { name: "Pesquisa em LP", credits: 2, code: "LEV488", requirements: [2,8,15,21,27,33,38], semester: 8, category: 1, workload: 30},
    /*45*/ { name: "História da LP", credits: 4, code: "LEV310", requirements: [2,8,15,21,27,33,38], semester: 8, category: 1, workload: 60},
    /*46*/ { name: "Atividades Acad. Livre Escolha", credits: 1, semester: 8, category: 1, workload: 30},
    /*47*/ { name: "Ativ. Compl. Especiais", credits: 405, semester: 8, step: 15, category: 5, workload: 405},
    /*48*/ { name: "MONOGRAFIA", credits: 160, code: "LEWX01", semester: 8, category: 1, workload: 160},
    ]
]
